### ISSUE TITLE
FeatureRequest: (Biome) maps for Real Solar System

### ISSUE THREAD

**Issue by embix** [Obrelix/KSPTools#1]
As the delta v calculator already supports RSS as well as Outer Planets, it would be cool to have maps for them too. Currently I have earth moon and mars in mind as those a realistic targets for the usual guy. Not only biome maps but also height and delta/height maps in general to find suitable landing sites.

**Comment by Obrelix** [comment]
@embix Hello mate! I hope you found useful this app and you will use it for your interplanetary missions! 
I will add all the Biome Maps for the outer planets mod!  But i think that on the RSS mod only earth has Biomes.. If you know that this is false let me know !

**Comment by embix** [comment]
I like the App and look forward to using it for my RSS Missions to come. I already did a moon landing in RSS with an Apollo-like approach (unfortunatly with loo less delta v to get back into moon orbit) but don't remember biomes. I can check about moon biomes this weekend.

**Comment by Obrelix** [comment]
Hello again!! I just found the Biome Maps for the RSS!
https://github.com/KSP-RO/RSS-Textures/tree/master/Biomes
I will add them to the app in a future update.. Now i am working to add some features to the Mission Calculator Tool  such as drawing and calculating the ejection angle and drawing the Phase Angle.

**Comment by Obrelix** [comment]
Hello mate! I just added all the available from the community biome maps! and made some changes to the Biom Maps Tool and DV Maps Tool! You can download the KSPToolEXEV0900.zip file and use it!

**Comment by embix** [comment]
Wow.  BTW: It sould be possible (never done that so far) to create a release.  That way you can keep sources and output separate while your binary release is linked to a specific commit and doesn't clutter up the repo.

**Comment by Obrelix** [comment]
hmmm i am new in the  github and i don't know a lot of things... do you have any guide for this?

**Comment by embix** [comment]
Not yet, but I'll try to set a release for one of my fiddle-around repos. The github documentation looks promising so far: https://help.github.com/search/?utf8=%E2%9C%93&q=release

**Comment by Obrelix** [comment]
Thank you dude!!! Do you have any other suggestion for this application?

**Comment by embix** [comment]
Not yet :smile: but that will come up when using KSPTools.

**Comment by Obrelix** [comment]
Ok nice! So i will close this issue ! You can post any suggestion to the forum thread if you like. 
http://forum.kerbalspaceprogram.com/index.php?/topic/143812-ksp-tools/
